#cloud-config
# source: https://thenewstack.io/deploy-a-kubernetes-cluster-on-ubuntu-server-with-microk8s/
users:
    - name: ubuntu
      sudo: ALL=(ALL) NOPASSWD:ALL
      groups: users, admin, microk8s
      home: /home/ubuntu
      shell: /bin/bash
      ssh_authorized_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCUBo+qnNu5xxM9vfz4C04M36FHxHNrEMdm5TkFj1/SfVtqunlUOeMpu7nFCZZKnX8HYwf/MkjcBiTYAgncxku8grwl6XuW/pcvmb6/ghSIaw4xtRRSzit7omqJ5d8kXB3+Nd1aaMHsjfly4nkaqswhySVXQqr8Hw6DbWVw8jLLVKEE+5NZHY33hJkhJwK4blCllsGpmQaKi1qxjsN0hZOWNK01iJAydwD8t2xJ0NOYbq8Qas5IyPnRN7SPxvEhIP6WLQ6Ym6Dmf8FwNW1cHLTKabgjzt5f/HKUkKS89dPd3fn4nnFli1BOMECGUIvVlOw2pQNri7+04OOfn2FGlqr5 teacher
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCyO3wvMB0/SC1qI5eTdyTxzhe0QlDVsGvhEapZoDFsn3L3UtXj7RjjnjQDeHpfA5z1utU9706T/PTWwbZElCq7+umfIIJPvMEjiUvrguRpWEHD8v81nGeSPJKCk4t5UI49WRGOc69Ro11C3ilpYNizsc40ntJHolYpXnfbJ3ExHdM0E/9BZcGFtmgFB3N8mgXLj2eTPC9wzIIPeInRZ3iVYyK7d3tRNZAgz7q2nDS5k8Le5ZlLJqM8WxL/5/TCIfj0szfOIt84nXng2QW6QW09nIuSyby7DrT4wRiSlpGzOXVYAO2aNUSRRhVzcS85RdcT+vho9I1Fw86JhSX+rdJH My-Key

groups:
    - microk8s
system_info:
    default_user:
        groups: [microk8s]
ssh_pwauth: false
disable_root: false
package_update: true
package_upgrade: true
packages:
    - curl
runcmd:
    - sudo snap install microk8s --classic
    - mkdir /home/ubuntu/.kube